CREATE DATABASE FINDINMAP;
USE FINDINMAP;

CREATE TABLE USERS(
	ID_USER INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(45),
    USER_EMAIL VARCHAR(30),
    USER_PASSWORD VARCHAR(45),
    ID_ROLUSER INT,
	FOREIGN KEY (ID_ROLUSER) REFERENCES ROL_USERS(ID_ROLUSER)
)ENGINE=INNODB;

CREATE TABLE ROL_USERS(
	ID_ROLUSER INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ROL VARCHAR(45)
)ENGINE=INNODB;

CREATE TABLE SELL_USERS(
	ID_SELLUSER INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ADDRESS VARCHAR(50),
    PHONE_NUMBER NUMERIC,
    SHOP_NAME VARCHAR(45),
    NIT VARCHAR(20),
    PAYMENT_TYPE ENUM('TPV','CASH','PayPal')
)ENGINE=INNODB;

CREATE TABLE PURCHASES(
	ID_PURCHASE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    QUANTITY_PURCHASE INT,
    TOTAL_PRICE DOUBLE,
    ID_PRODUCT INT,
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT)
)ENGINE=INNODB;

CREATE TABLE PRODUCTS(
	ID_PRODUCT INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PROD_NAME VARCHAR(20),
    PROD_PRICE DOUBLE,
    PROD_STOCK INT,
    PROD_PHOTO BLOB,
    PROD_DESCRIPTION MEDIUMTEXT,
    PROD_MANUFACT_DATE DATE,
	PROD_MANUFACT_TYPE VARCHAR(100)
	ID_SELLUSER INT,
	FOREIGN KEY (ID_SELLUSER) REFERENCES SELL_USERS(ID_SELLUSER)
)ENGINE=INNODB;

CREATE TABLE TYPE_SENDS(
	ID_TYPESEND INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SEND ENUM('CORREOS','COMANDITAS'),
    PRICE_SEND DOUBLE
)ENGINE=INNODB;

CREATE TABLE TAGS(
	ID_TAG IN PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TAGNAME VARCHAR(200)
)ENGINE=INNODB;

CREATE TABLE POSTS(
	ID_POST INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_PRODUCT INT,
    ID_TYPESEND INT,
	ID_TAG INT,
	FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT),
	FOREIGN KEY (ID_TYPESEND) REFERENCES TYPE_SENDS(ID_TYPESEND),
	FOREIGN KEY (ID_TAG) REFERENCES TAGS(ID_TAG)
)ENGINE=INNODB;

CREATE TABLE COMMENTARIES(
	ID_COMMENTARY INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATE_COMMENT DATE,
    COMMENTARY MEDIUMTEXT,
    PHOTO_PRODUCT BLOB,
    ID_USER INT,
	FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER)
)ENGINE=INNODB;
